#!/usr/bin/env bash
# Install and configure a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 1187-web-01 35.237.103.2:80 check\n\tserver 1187-web-02 18.209.63.81:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
